language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: roYBtXeZu4n1qafgATYEjWadkYcwmJG6ng4jWnltKWyJzoAIfzhzX5pmkK5lcfU7HT8WJ2faLPQW5EzZ4S5vRLYRMG2SIc1nTOCtfPSoJXALk6T2EcXldGLN4ObDOW6S85O8ovdrN/AIez7IHrVO2dZXDINjQdYUJVKlP8pBanW/m+Fc3gv4YtlbiJ1gLBHPFgsEs1mDPVHmlrUCCeCnOAyryaBFbLLAP9EVYsYtNUQK1cmqIi3Fg6RdfMWp3PLc8QgQyY7emngk1QqEMOs7GG0YP+a/oIu2KHzwuHcxUbchSReFokb2cOuqJsv32SKxmEI5nMQk23jKryYxRIrunKgepol00b+PxOYMEiIMHXCulC+UI4AWJ2t2jxIGZilXJIMq94zcTG9UBDI+gCeUCGqz2vUuKNfe9tJ9i4tMoXf9RcJRrXS0plUCFF77C217BskaJEyKIJVgXxCSBslWfIa4tLBNYmOCA5tNr2OcGeIzM9MY8whFHvdtYYHEPznm5q+2/XeHs1MURDZMOkallbQZEYGgBcYA6A7BY8W2XVFy1GMLctdinmwL4tshm82XzP+LBYDluSsqf/ErFIKYUFgy2H80dbNCmBucvPcUZB98AbbALSmPR7NBmhwPsFqZwGAdLPX5qq7slwNd+TKYrUXtrXyixdsRlrLXDt9PIKE=
